### ISSUE TITLE
deployments/nginx-app 예제 관련 수정 요청

### ISSUE THREAD

**Issue by kbpark9898** [arisu1000/kubernetes-book-sample#2]
책 part 1의 3장에서 https://github.com/arisu1000/kubernetes-book-sample/blob/master/deployment/nginx-app.yaml 를 이용한 nginx-app 을 서비스하는 예제를 진행합니다.

이 과정에서 현재 docker의 nginx 공식 이미지를 사용해 컨테이너를 생성하고 nginx 서버를 실행시키면, 기본 리스닝 포트가 80으로 설정되어 있습니다.
하지만 이 레포에 있는 [nginx-app.yaml](https://github.com/arisu1000/kubernetes-book-sample/blob/master/deployment/nginx-app.yaml)은 컨테이너의 기본 서비스 포트를 8080으로 설정하고 있기 때문에, NodePort서비스를 이용해 터널링 해줘도 컨테이너에서 서비스되고있는 nginx가 사용자의 요청을 제대로 수신하지 못합니다.

따라서 해당 예제를 제대로 실행하기 위해서는 다음 두가지 과정 중 한가지를 거쳐야 합니다.

1. [nginx-app.yaml](https://github.com/arisu1000/kubernetes-book-sample/blob/master/deployment/nginx-app.yaml)의 컨테이너 리스닝 포트를 80으로 수정할 것.
2. 예제 파일을 그대로 이용하여 deployment를 실행하되, 실행중인 컨테이너에 직접 접속하여 nginx 설정파일의 default port를 8080으로 수정하고 pod에 exec 커맨드를 통해 nginx 재시작을 명령할 것.

이 해결방안 중 2번 해결방안은 nginx 및 컨테이너 시스템에 대한 이해가 기반되지 않은 상태에서는 수행하기 어려워 책을 통해 쿠버네티스를 처음 학습하는데 걸림돌이 될 수 있을것 같습니다.

따라서 1번 해결방안을 위해 [nginx-app.yaml](https://github.com/arisu1000/kubernetes-book-sample/blob/master/deployment/nginx-app.yaml)의 수정 요청을 드립니다. 

직접 수정이 어려우시다면 제가 저장소를 fork하여 PR을 생성해도 되는지 여쭙고 싶습니다.

**Comment by arisu1000** [comment]
@kbpark9898 안녕하세요. 자세히 살펴보고 의견 주셔서 감사합니다.
제가 직접 수정해도 되지만 @kbpark9898 께서 발견해주신거니 PR 해 주시면 머지하도록 할께요~

**Comment by kbpark9898** [comment]
휴일임에도 빠른 답변 감사합니다. 빠른 반영 위해 PR 드렸습니다!

**Comment by arisu1000** [comment]
@kbpark9898 머지했어요. PR 감사합니다.
