### ISSUE TITLE
wordpress/wordpress.yaml 에러

### ISSUE THREAD

**Issue by ha2hi** [arisu1000/kubernetes-book-sample#4]
안녕하세요 @arisu1000 
[wordpress/wordpress.yaml](https://github.com/arisu1000/kubernetes-book-sample/blob/master/wordpress/wordpress.yaml)을 실행하면서  2가지 에러가 있었습니다.
**1. Deployment의 apiVersion
2. wordpress env**

1. Deployment의 apiVersion
https://github.com/arisu1000/kubernetes-book-sample/blob/7e4bd667496004278b6c40326a63249c92561ca4/wordpress/wordpress.yaml#L17
"extensions/v1beta1" -> "apps/v1"으로 수정과 `spec.replicas`, `spec.selector` 코드 추가가 필요해보입니다.

2. wordpress env
https://github.com/arisu1000/kubernetes-book-sample/blob/7e4bd667496004278b6c40326a63249c92561ca4/wordpress/wordpress.yaml#L28-L41
기존 환경설정을 그대로 사용하면 "Error establishing a database connection"에러가 발생하였고 아래와 같이 추가적으로 설정하여 해결했습니다.
```
        - name: WORDPRESS_DB_NAME
          value: mysql
        - name: WORDPRESS_DB_USER
          value: root
```

**Comment by arisu1000** [comment]
@ha2hi 안녕하세요. 
아무래도 예제가 만들어진지 시간이 좀 흐르다 보니 노후화로 인해 이런 이슈가 있는 것 같습니다.
알려 주셔서 감사합니다^^

**Comment by arisu1000** [comment]
반영완료 : [6be60a6155a2febff4f7bfe22f168c0fe3a2b7cb](https://github.com/arisu1000/kubernetes-book-sample/commit/6be60a6155a2febff4f7bfe22f168c0fe3a2b7cb)
